# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:

  orderer.ipsum.io:
    container_name: orderer.ipsum.io
    image: hyperledger/fabric-orderer:$IMAGE_TAG
    environment:
      - ORDERER_GENERAL_LOGLEVEL=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
    - /etc/fabric/channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
    - /etc/fabric/crypto-config/ordererOrganizations/ipsum.io/orderers/orderer.ipsum.io/msp:/var/hyperledger/orderer/msp
    - /etc/fabric/crypto-config/ordererOrganizations/ipsum.io/orderers/orderer.ipsum.io/tls/:/var/hyperledger/orderer/tls
    - orderer.ipsum.io:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  peer0.univ1.ipsum.io:
    container_name: peer0.univ1.ipsum.io
    extends:
      file: peer-base.yaml
      service: peer-base
    image: hyperledger/fabric-peer:$IMAGE_TAG
    environment:
      - CORE_PEER_ID=peer0.univ1.ipsum.io
      - CORE_PEER_ADDRESS=peer0.univ1.ipsum.io:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.univ1.ipsum.io:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.univ1.ipsum.io:7051
      - CORE_PEER_LOCALMSPID=univ1MSP
    volumes:
        - /var/run/:/host/var/run/
        - /etc/fabric/crypto-config/peerOrganizations/univ1.ipsum.io/peers/peer0.univ1.ipsum.io/msp:/etc/hyperledger/fabric/msp
        - /etc/fabric/crypto-config/peerOrganizations/univ1.ipsum.io/peers/peer0.univ1.ipsum.io/tls:/etc/hyperledger/fabric/tls
        - peer0.univ1.ipsum.io:/var/hyperledger/production
    ports:
      - 7051:7051
      - 7053:7053

  peer0.univ2.ipsum.io:
    container_name: peer0.univ2.ipsum.io
    extends:
      file: peer-base.yaml
      service: peer-base
    image: hyperledger/fabric-peer:$IMAGE_TAG
    environment:
      - CORE_PEER_ID=peer0.univ2.ipsum.io
      - CORE_PEER_ADDRESS=peer0.univ2.ipsum.io:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.univ2.ipsum.io:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.univ2.ipsum.io:7051
      - CORE_PEER_LOCALMSPID=univ2MSP
    volumes:
        - /var/run/:/host/var/run/
        - /etc/fabric/crypto-config/peerOrganizations/univ2.ipsum.io/peers/peer0.univ2.ipsum.io/msp:/etc/hyperledger/fabric/msp
        - /etc/fabric/crypto-config/peerOrganizations/univ2.ipsum.io/peers/peer0.univ2.ipsum.io/tls:/etc/hyperledger/fabric/tls
        - peer0.univ2.ipsum.io:/var/hyperledger/production
    ports:
      - 8051:7051
      - 8053:7053

  peer0.univ3.ipsum.io:
    container_name: peer0.univ3.ipsum.io
    extends:
      file: peer-base.yaml
      service: peer-base
    image: hyperledger/fabric-peer:$IMAGE_TAG
    environment:
      - CORE_PEER_ID=peer0.univ3.ipsum.io
      - CORE_PEER_ADDRESS=peer0.univ3.ipsum.io:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.univ3.ipsum.io:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.univ3.ipsum.io:7051
      - CORE_PEER_LOCALMSPID=univ3MSP
    volumes:
        - /var/run/:/host/var/run/
        - /etc/fabric/crypto-config/peerOrganizations/univ3.ipsum.io/peers/peer0.univ3.ipsum.io/msp:/etc/hyperledger/fabric/msp
        - /etc/fabric/crypto-config/peerOrganizations/univ3.ipsum.io/peers/peer0.univ3.ipsum.io/tls:/etc/hyperledger/fabric/tls
        - peer0.univ3.ipsum.io:/var/hyperledger/production
    ports:
      - 9051:7051
      - 9053:7053
