# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer.ipsum.io:
  peer0.org1.ipsum.io:
  peer0.org2.ipsum.io:
  peer0.org3.ipsum.io:
  pgdata:
  walletstore:

networks:
  byfn:

services:
  ca.ipsum.io:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.scriptum.com
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.ipsum.io-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/a9a3e67e101a3cb667bfc5ed3c122eda61025d798794d49b926bed51d93d20f3_sk
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw'
    volumes:
      - /etc/fabric/crypto-config/peerOrganizations/org1.ipsum.io/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.ipsum.io
    networks:
      - byfn 
 
  orderer.ipsum.io:
    extends:
      file:   docker-compose-base.yaml
      service: orderer.ipsum.io
    container_name: orderer.ipsum.io
    networks:
      - byfn

  peer0.org1.ipsum.io:
    container_name: peer0.org1.ipsum.io
    extends:
      file: docker-compose-base.yaml
      service: peer0.org1.ipsum.io
    networks:
      - byfn

  peer0.org2.ipsum.io:
    container_name: peer0.org2.ipsum.io
    extends:
      file:  docker-compose-base.yaml
      service: peer0.org2.ipsum.io
    networks:
      - byfn

  peer0.org3.ipsum.io:
    container_name: peer0.org3.ipsum.io
    extends:
      file:  docker-compose-base.yaml
      service: peer0.org3.ipsum.io
    networks:
      - byfn

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- CORE_LOGGING_LEVEL=DEBUG
      - CORE_LOGGING_LEVEL=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.org1.ipsum.io:7051
      - CORE_PEER_LOCALMSPID=org1MSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.ipsum.io/peers/peer0.org1.ipsum.io/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.ipsum.io/peers/peer0.org1.ipsum.io/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.ipsum.io/peers/peer0.org1.ipsum.io/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.ipsum.io/users/Admin@org1.ipsum.io/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - /etc/fabric/chaincode/:/opt/gopath/src/github.com/chaincode
        - /etc/fabric/crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - /etc/fabric/scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - /etc/fabric/channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
        - /etc/fabric/tools-bin/:/opt/gopath/src/github.com/hyperledger/fabric/tools-bin
        - /etc/fabric/network-management-scripts/:/opt/gopath/src/github.com/hyperledger/fabric/network-management-scripts
    depends_on:
      - orderer.ipsum.io
      - peer0.org1.ipsum.io
      - peer0.org2.ipsum.io
      - peer0.org3.ipsum.io
    networks:
      - byfn

  explorerdb.ipsum.io:
    container_name: explorerdb.ipsum.io
    image: hyperledger/explorer-db:latest
    environment:
      - DATABASE_DATABASE=fabricexplorer
      - DATABASE_USERNAME=hppoc
      - DATABASE_PASSWORD=password
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - ../explorer/db/:/docker-entrypoint-initdb.d/
      - pgdata:/var/lib/postgresql/data
    networks:
      - byfn

  fabric-explorer:
    container_name: fabric-explorer
    image: hyperledger/explorer:latest
    ports:
      - "8090:8080"
    depends_on:
      - explorerdb.ipsum.io
      - orderer.ipsum.io
      - peer0.org1.ipsum.io
      - peer0.org2.ipsum.io
      - peer0.org3.ipsum.io
    environment:
      - DATABASE_HOST=explorerdb.ipsum.io
      - DATABASE_USERNAME=hppoc
      - DATABASE_PASSWD=password
      - DISCOVERY_AS_LOCALHOST=false
    networks:
      - byfn
    volumes:
      - ../explorer/config.json:/opt/explorer/app/platform/fabric/config.json
      - ../explorer/connection-profile:/opt/explorer/app/platform/fabric/connection-profile
      - /etc/fabric/crypto-config:/tmp/crypto
      - walletstore:/opt/wallet
    command: sh -c "sleep 16&& node /opt/explorer/main.js && tail -f /dev/null"
